USE [master]
GO
/****** Object:  Database [FeiraDB]    Script Date: 10/03/2022 00:19:35 ******/
CREATE DATABASE [FeiraDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FeiraDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FeiraDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FeiraDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FeiraDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FeiraDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FeiraDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FeiraDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FeiraDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FeiraDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FeiraDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FeiraDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FeiraDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FeiraDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FeiraDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FeiraDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FeiraDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FeiraDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FeiraDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FeiraDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FeiraDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FeiraDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FeiraDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FeiraDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FeiraDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FeiraDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FeiraDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FeiraDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FeiraDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FeiraDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FeiraDB] SET  MULTI_USER 
GO
ALTER DATABASE [FeiraDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FeiraDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FeiraDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FeiraDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FeiraDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FeiraDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FeiraDB', N'ON'
GO
ALTER DATABASE [FeiraDB] SET QUERY_STORE = OFF
GO
USE [FeiraDB]
GO
/****** Object:  Table [dbo].[TBL_DISTRITOS]    Script Date: 10/03/2022 00:19:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_DISTRITOS](
	[CODDIST] [int] IDENTITY(1,1) NOT NULL,
	[DISTRITO] [varchar](18) NOT NULL,
 CONSTRAINT [PK_TBL_DISTRITOS] PRIMARY KEY CLUSTERED 
(
	[CODDIST] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_FEIRAS]    Script Date: 10/03/2022 00:19:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_FEIRAS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LONG] [int] NOT NULL,
	[LAT] [int] NOT NULL,
	[SETCENS] [varchar](15) NOT NULL,
	[AREAP] [varchar](13) NOT NULL,
	[CODDIST] [int] NOT NULL,
	[CODSUBPREF] [int] NOT NULL,
	[REGIAO5] [varchar](6) NOT NULL,
	[REGIAO8] [varchar](7) NOT NULL,
	[NOME_FEIRA] [varchar](30) NOT NULL,
	[REGISTRO] [varchar](6) NOT NULL,
	[LOGRADOURO] [varchar](34) NOT NULL,
	[NUMERO] [varchar](15) NULL,
	[BAIRRO] [varchar](20) NULL,
	[REFERENCIA] [varchar](30) NULL,
 CONSTRAINT [PK_TBL_FEIRAS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TBL_SUBPREFEITURAS]    Script Date: 10/03/2022 00:19:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_SUBPREFEITURAS](
	[CODSUBPREF] [int] IDENTITY(1,1) NOT NULL,
	[SUBPREF] [varchar](25) NOT NULL,
 CONSTRAINT [PK_TBL_SUBPREFEITURAS] PRIMARY KEY CLUSTERED 
(
	[CODSUBPREF] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TBL_FEIRAS]  WITH CHECK ADD  CONSTRAINT [FK_Feira_Subprefeitura_Id] FOREIGN KEY([CODSUBPREF])
REFERENCES [dbo].[TBL_SUBPREFEITURAS] ([CODSUBPREF])
GO
ALTER TABLE [dbo].[TBL_FEIRAS] CHECK CONSTRAINT [FK_Feira_Subprefeitura_Id]
GO
ALTER TABLE [dbo].[TBL_FEIRAS]  WITH CHECK ADD  CONSTRAINT [FK_Feiras_Distritos_Id] FOREIGN KEY([CODDIST])
REFERENCES [dbo].[TBL_DISTRITOS] ([CODDIST])
GO
ALTER TABLE [dbo].[TBL_FEIRAS] CHECK CONSTRAINT [FK_Feiras_Distritos_Id]
GO
USE [master]
GO
ALTER DATABASE [FeiraDB] SET  READ_WRITE 
GO
