USE FeiraDB
GO

DECLARE @PATH_DEINFO_AB_FEIRASLIVRES_2014 VARCHAR(256)
SET @PATH_DEINFO_AB_FEIRASLIVRES_2014 = 'C:\Users\bruna\source\repos\feira-livre-api\database\DEINFO_AB_FEIRASLIVRES_2014.csv'

BEGIN TRY
    BEGIN TRANSACTION;
        CREATE TABLE #TMP_TBL_FEIRAS(
			[ID] [int] NULL,
			[LONG] [int] NULL,
			[LAT] [int] NULL,
			[SETCENS] [varchar](15) NULL,
			[AREAP] [varchar](13) NULL,
			[CODDIST] [int] NULL,
			[DISTRITO] [varchar](18) NULL,
			[CODSUBPREF] [int] NULL,
			[SUBPREF] [varchar](25) NULL,
			[REGIAO5] [varchar](6) NULL,
			[REGIAO8] [varchar](7) NULL,	
			[NOME_FEIRA] [varchar](30) NULL,
			[REGISTRO] [varchar](6) NULL,
			[LOGRADOURO] [varchar](34) NULL,
			[NUMERO] [varchar](15) NULL,
			[BAIRRO] [varchar](20) NULL,
			[REFERENCIA] [varchar](30) NULL
		)
 
		-- import the file
		BULK INSERT #TMP_TBL_FEIRAS
		FROM 'C:\Users\bruna\source\repos\feira-livre-api\database\DEINFO_AB_FEIRASLIVRES_2014.csv'
		WITH
		(
			FORMAT='CSV',
			FIRSTROW=2,
			LASTROW=880
		)
		
		SET IDENTITY_INSERT dbo.TBL_DISTRITOS ON

		INSERT INTO dbo.TBL_DISTRITOS(
			CODDIST, 
			DISTRITO
		)
		SELECT DISTINCT
			CODDIST,
			DISTRITO
		FROM #TMP_TBL_FEIRAS

		SET IDENTITY_INSERT dbo.TBL_DISTRITOS OFF

		SET IDENTITY_INSERT dbo.TBL_SUBPREFEITURAS ON

		INSERT INTO dbo.TBL_SUBPREFEITURAS(
			CODSUBPREF, 
			SUBPREF
		)
		SELECT DISTINCT
			CODSUBPREF,
			SUBPREF
		FROM #TMP_TBL_FEIRAS

		SET IDENTITY_INSERT dbo.TBL_SUBPREFEITURAS OFF


		SET IDENTITY_INSERT dbo.TBL_FEIRAS ON

		INSERT INTO dbo.TBL_FEIRAS(
			ID,
			LONG,
			LAT,
			SETCENS,
			AREAP,
			CODDIST,	
			CODSUBPREF,	
			REGIAO5,
			REGIAO8,
			NOME_FEIRA,
			REGISTRO,
			LOGRADOURO,
			NUMERO,
			BAIRRO,
			REFERENCIA
		)
		SELECT
			ID,
			LONG,
			LAT,
			SETCENS,
			AREAP,
			CODDIST,	
			CODSUBPREF,	
			REGIAO5,
			REGIAO8,
			NOME_FEIRA,
			REGISTRO,
			LOGRADOURO,
			NUMERO,
			BAIRRO,
			REFERENCIA
		FROM #TMP_TBL_FEIRAS

		SET IDENTITY_INSERT dbo.TBL_FEIRAS OFF
		
		DROP TABLE #TMP_TBL_FEIRAS

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        BEGIN
            ROLLBACK TRANSACTION;
        END;
 
    DECLARE @ERROR_SEVERITY INT,
            @ERROR_STATE INT,
            @ERROR_NUMBER INT,
            @ERROR_LINE INT,
            @ERROR_MESSAGE NVARCHAR(4000);
 
    SELECT @ERROR_SEVERITY = ERROR_SEVERITY(),
           @ERROR_STATE = ERROR_STATE(),
           @ERROR_NUMBER = ERROR_NUMBER(),
           @ERROR_LINE = ERROR_LINE(),
           @ERROR_MESSAGE = ERROR_MESSAGE();
 
    RAISERROR('Msg %d, Line %d, :%s', @ERROR_SEVERITY, @ERROR_STATE, @ERROR_NUMBER, @ERROR_LINE, @ERROR_MESSAGE);
END CATCH;